<a href="https://colab.research.google.com/github/lyviaborgeelias/Machine_Learning/blob/main/aula2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ARVORE DE DESCISÃO

In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier #classificador da árvore de decisão
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.tree import export_graphviz #gerar a árvore de decisão
import graphviz

base = pd.read_csv('insurance.csv')
base

base = base.drop(columns= ['Unnamed: 0'])

In [7]:
y = base.iloc[:,7].values
X = base.iloc[:,[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]].values

labelencoder = LabelEncoder()

for i in range(X.shape[1]):
  if X[:,i].dtype == 'object':
    X[:,i] = labelencoder.fit_transform(X[:,i])

y = labelencoder.fit_transform(y)

X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X,y,test_size=0.3, random_state=1)

In [8]:
base.iloc[:,0].values

array([False, False, False, ..., False, False, False])

In [10]:

modelo = DecisionTreeClassifier(random_state=1)
modelo.fit(X_treinamento, y_treinamento)

previsoes = modelo.predict(X_teste)
previsoes

accuracy = accuracy_score(y_teste, previsoes)
precision = precision_score(y_teste, previsoes, average='weighted')
recall = recall_score(y_teste, previsoes, average='weighted')
f1 = f1_score(y_teste, previsoes, average='weighted')
print(f'Acuracia: {accuracy}, Precisão: {precision}, Recall {recall}, F1: {f1}')

Acuracia: 0.9193333333333333, Precisão: 0.9205163849870271, Recall 0.9193333333333333, F1: 0.9197596677057858


In [11]:
dot_data = export_graphviz(modelo, out_file=None, filled=True, feature_names=base.columns[:-1], class_names=True, rounded=True) #pegando todas as colunas
graph = graphviz.Source(dot_data)
graph.render("decision_tree", format="png")
graph.view() #gera o arquivo

dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.563559 to fit


'decision_tree.pdf'

In [13]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import pandas as pd
import numpy as np

mtcars = pd.read_csv('mt_cars.csv')
mtcars.head()

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2


In [15]:
X = mtcars[['mpg','hp']].values #utilizar esse par de valores como X para prever número de cilindros
y = mtcars['cyl'].values

knn = KNeighborsClassifier(n_neighbors=3)
modelo = knn.fit(X,y)

y_prev = modelo.predict(X) #fazendo a previsão com o mesmo X já que não separamos conjunto de teste
print(y_prev) #teriamos carros de 4, 6 e 8 cilindros

[6 6 4 6 8 6 8 4 4 6 6 8 8 8 8 8 8 4 4 4 4 8 8 8 8 4 4 4 8 8 8 6]


In [16]:
accuracy = accuracy_score(y, y_prev)
precision = precision_score(y, y_prev, average='weighted')
recall = recall_score(y, y_prev, average='weighted')
f1 = f1_score(y, y_prev, average='weighted')
cm = confusion_matrix(y, y_prev)
print(f'Acuracia: {accuracy}, Precisão: {precision}, Recall {recall}, F1: {f1}')
print
print('Matriz de confusão:\n', cm)

Acuracia: 0.9375, Precisão: 0.9395833333333333, Recall 0.9375, F1: 0.9372947454844006
Matriz de confusão:
 [[10  1  0]
 [ 0  6  1]
 [ 0  0 14]]


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import pandas as pd
import numpy as np

mtcars = pd.read_csv('mt_cars.csv')
mtcars.head()


X = mtcars[['mpg','hp']].values #utilizar esse par de valores como X para prever número de cilindros
y = mtcars['cyl'].values

knn = KNeighborsClassifier(n_neighbors=3)
modelo = knn.fit(X,y)

y_prev = modelo.predict(X) #fazendo a previsão com o mesmo X já que não separamos conjunto de teste
print(y_prev) #teriamos carros de 4, 6 e 8 cilindros

In [17]:
from sklearn import datasets #utilizaremos conuntos de dados da própria lib
from sklearn.metrics import confusion_matrix
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN #os dois últimos são hierárquicos
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import linkage, dendrogram #árvore de clusters

iris = datasets.load_iris() #conjunto de dados clássico utilizado em machine learning
iris
#3 argumento numéricos -> largura da flor de iris (sépala, pétala, área) de flor de iris
#1 classe -> nome da flor! Aqui está discretizado

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [20]:
iris = datasets.load_iris() #conjunto de dados clássico utilizado em machine learning
iris
#3 argumento numéricos -> largura da flor de iris (sépala, pétala, área) de flor de iris
#1 classe -> nome da flor! Aqui está discretizado

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [19]:
kmeans = KMeans(n_clusters=3,n_init='auto') #precisa definir número de clusters, e a inicialização vai ser automática
kmeans.fit(iris.data) #só vai trazer as 4 primeiras colunas mostradas anteriormente | iris.target traz a classe
print(kmeans.labels_) #aqui poderemos ver que cada instância está sendo atribuída a um cluster
#com print(iris.target) vê-se que as classes estão bem definidas! não misturadas
#isso mostra que no kmeans, houve alguns erros
#gerar uma marriz de confusão para mostrar a comparação de ambos
resultados = confusion_matrix(iris.target, kmeans.labels_)
print(resultados) #vai mostrar resultados ligeiramente diferentes pois não existe equivalência entre o índice do cluster e o índice da classe

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 0 0 0 0 2 0 0 0 0
 0 0 2 2 0 0 0 0 2 0 2 0 2 0 0 2 2 0 0 0 0 0 2 0 0 0 0 2 0 0 0 2 0 0 0 2 0
 0 2]
[[ 0 50  0]
 [ 3  0 47]
 [36  0 14]]


In [18]:
#eps -> circunferência ao redor de cada ponto
#min_samples -> número mínimo de dados para estar dentro do eps p/ n ser ruído
#quando mais você aumentar isso, menos ruído terá!
dbscan = DBSCAN(eps=0.5, min_samples=3)
dbscan_labels = dbscan.fit_predict(iris.data)
print(dbscan_labels)

[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 -1  0  0  0  0  0  0
  0  0  1  1  1  1  1  1  1  2  1  1  2  1  1  1  1  1  1  1 -1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1  1  1  1  1  1  2  1  1
  1  1  2  1  1  1  1  1  1  3 -1  1 -1 -1  1  1  1  1  1  1  1 -1  3  1
  1  1  3  1  1  1  1  1  1  1  1 -1  1  1 -1 -1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1]
